### ISSUE TITLE
Some UWP asset icons are missing

### ISSUE THREAD

**Issue by Lolihunter1337** [ThatsNiceGuy/osu-uwp#1]
**Describe the bug:** 

Just a small thing i found so far the rest works as it should ^^. 

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/17437302/68357157-b7a15a00-0114-11ea-97f7-347c0f43363a.png)
![image](https://user-images.githubusercontent.com/17437302/68357162-bb34e100-0114-11ea-980f-24d9bb5376a8.png)

**osu!lazer version:** 

osu.UWP-2019.1106.0

**Logs:** 
shouldnt be needed 

**Running as standard Windows.exe or a UWP app?**
UWP

**Comment by ThatsNiceGuy** [comment]
properly generate more assets soon probably coming alongside the next official osu!lazer release

**Comment by ThatsNiceGuy** [comment]
Should be fixed with latest UWP release. Close issue if fixed
